baseURL = "/"
languageCode = "en-gb"
title = "Fullstack Digital"
theme = ["pancakes-builder", "pancakes"]

ignorefiles = [ "admin", "docs" ]
enableRobotsTXT = true
disableAliases = true
disableKinds = ["taxonomy","taxonomyTerm"]

[permalinks]
  pages = "/:section/:title/"
  blog = "/:title/"
  work = "/:sections/:slug/"

[params]
disallow_search_engines = false # set robots.txt to disallow everything
debug_enabled = false
# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

